export const SET_TOR_FILTER_DATA = 'SET_TOR_FILTER_DATA';
export const RESET_TOR_FILTER_DATA = 'RESET_TOR_FILTER_DATA';
export const RESET_TOR_PARAMETERS = 'RESET_TOR_PARAMETERS';
export const RESET_TOR_FILTER = 'RESET_TOR_FILTER';
