export const SET_TOR_FILTER = 'SET_TOR_FILTER';
export const SET_BULK_TOR_FILTER = 'SET_BULK_TOR_FILTER';
export const RESET_TOR_FILTER = 'RESET_TOR_FILTER';
export const IS_TOR_FILTER_IS_RESET = 'IS_TOR_FILTER_IS_RESET';
