export const SET_TOR_RECOMMENDATION = 'SET_TOR_RECOMMENDATION';
export const SET_BULK_TOR_RECOMMENDATION = 'SET_BULK_TOR_RECOMMENDATION';
export const RESET_TOR_RECOMMENDATION = 'RESET_TOR_RECOMMENDATION';
