export const SET_IM_TEST_TEMPLATE_FORMDATA = 'SET_IM_TEST_TEMPLATE_FORMDATA';
export const SET_BULK_IM_TEST_TEMPLATE_FORMDATA = 'SET_BULK_IM_TEST_TEMPLATE_FORMDATA';
export const RESET_IM_TEST_TEMPLATE_FORMDATA = 'RESET_IM_TEST_TEMPLATE_FORMDATA';
