/** import React, PropTypes and React router dom */
import React from 'react';
import PropTypes from 'prop-types';
import { Link } from 'react-router-dom';

/** import Material UI styles and components */
import withStyles from '@material-ui/core/styles/withStyles';
import Typography from '@material-ui/core/Typography';

/** import configuration value and logo */
import { primaryColor } from '../config/colors';
import mainLogo from "../../../../img/immap-career-logo.png";

/**
 * AuthLogo is a component to show Logo in:
 *  - Login
 *  - Register
 *  - ResetPassword
 *  - ResetPasswordForm
 *  - FileViewer
 * Component
 *
 * @name AuthLogo
 * @component
 * @category Common
 *
 */
const AuthLogo = ({ classes }) => (
  <div>
    <Link to="/" className={classes.logoLink}>
      <img
        src={mainLogo}
        alt="immap career"
        className={classes.imgLogo}
      />{" "}
      <Typography variant="h5" className={classes.textLogo}>
        iMMAP Careers
      </Typography>
    </Link>
  </div>
);

AuthLogo.propTypes = {
  /**
   * classes is a prop containing styles for this component generated by material-ui v3
   */
  classes: PropTypes.object.isRequired
}

/**
 * set up styles for this component
 * @param {*} theme
 * @returns {object} classes prop to apply styles in the component
 */
const styles = (theme) => ({
  textLogo: {
    display: "inline-block",
    "vertical-align": "middle",
    "font-weight": "bold",
    color: primaryColor,
    "margin-top": (theme.spacing.unit / 2) * -1,
    "margin-left": theme.spacing.unit / 2,
  },
  imgLogo: {
    display: "inline-block",
    "vertical-align": "middle",
  },
  logoLink: {
    "text-decoration": "none",
  },
})

export default withStyles(styles)(AuthLogo);
