export const SET_IMMAPERS_FILTER = 'SET_IMMAPER_FILTER';
export const SET_BULK_IMMAPERS_FILTER = 'SET_BULK_IMMAPER_FILTER';
export const RESET_IMMAPERS_FILTER = 'RESET_IMMAPER_FILTER';
export const IS_IMMAPERS_FILTER_IS_RESET = 'IS_IMMAPER_FILTER_IS_RESET';
