/** import React, classname, Prop Types and Link */
import React from 'react';
import PropTypes from 'prop-types';

/** import Material UI styles and Component */
import { withStyles } from '@material-ui/core/styles';
import Typography from '@material-ui/core/Typography';

/** import React Redux and it's actions */
import { connect } from "react-redux";
import { postAPI } from '../redux/actions/apiActions';

/** import Components needed for this component */
import Jobs from './jobs/Jobs';
import OfficeAddress from '../common/OfficeAddress';
import ProfileUpdateRemind from './ProfileUpdateRemind'

/** import slider image */
import slideImg from '../../../../img/slide-corporate-fit.jpg';
import { blueIMMAP, primaryColor, white } from '../config/colors';

// set slider height value
const heightDefault = 450;

/**
 * set up styles for this component
 * @ignore
 * @param {object} theme
 * @returns {object} classes prop to apply styles in the component
 */
const styles = (theme) => ({
	bgNSearch: {
		height: heightDefault + 'px',
		background: 'url(' + slideImg + ')',
		position: 'relative'
	},
	jobOpening: {
		position: 'absolute',
		bottom: 0,
		padding: '.5em 0',
		width: '100%',
		'text-align': 'center',
		color: 'white',
		'font-weight': 'bold',
		background: 'rgba(0,0,0,0.5)'
	},
	maxWidth: {
		width: '100%',
		'text-align': 'center'
	},
	container: {
		padding: theme.spacing.unit * 3
	},
  paper: {
    paddingLeft: theme.spacing.unit * 3,
    paddingRight: theme.spacing.unit * 3,
    paddingTop: theme.spacing.unit * 2,
    paddingBottom: theme.spacing.unit * 2,
    marginBottom: theme.spacing.unit * 3,
    textAlign: 'center',
    border: 0
  },
  whiteText: { color: white, '& *': { color: `${white} !important` } },
  blueText: { color: blueIMMAP },
  defaultText: { color: primaryColor },
  blueBg: { background: blueIMMAP },
  defaultBg: { background: primaryColor },
});

/**
 * Home is a component to show Home page
 *
 * @name Home
 * @component
 * @category Page
 *
 */
const Home = ({ classes, history, match, location, user  }) => (
  <div>
    <div>
      <section id="bg-n-search" className={classes.bgNSearch}>
        <Typography variant="h2" className={classes.jobOpening}>
          Job Openings
        </Typography>
      </section>
    </div>
    <div className={classes.container}>
      <Jobs noTitle history={history} match={match} isHome={true} location={location}/>
    </div>
    <ProfileUpdateRemind
      isOpen={typeof history.location.state  !== 'undefined' && (user.data.profile.updated_profile == 0 || user.data.profile.updated_profile == '0') ? true : false}
      history={history}
    />
    <OfficeAddress />
  </div>
)

Home.propTypes = {
  /**
   * classes is a prop containing styles for this component generated by material-ui v3
   */
  classes: PropTypes.object.isRequired,
  /**
   * postAPI is a prop containing redux actions to call an api using POST HTTP Request
   */
  postAPI: PropTypes.func.isRequired,
}

/**
 * set up map dispatch to props for this component
 * @ignore
 * @property {object} mapDispatchToProps - contain redux actions to be used in component via props
 */
const mapDispatchToProps = {
  postAPI,
};

/**
 * set up map state to props for this component
 * @ignore
 * @param {object} state
 * @returns {object} all needed state data inside reducer that are mapped as a prop to be used in the component
 */
const mapStateToProps = (state) => ({
  user: state.auth.user,
});

export default withStyles(styles)(
  connect(
    mapStateToProps,
    mapDispatchToProps
  )(Home)
);
