export const IMMAPER_TAR_FORM_ADD_CONNECTION = 'IMMAPER_TAR_FORM_ADD_CONNECTION'
export const IMMAPER_TAR_FORM_DELETE_CONNECTION = 'IMMAPER_TAR_FORM_DELETE_CONNECTION'
export const IMMAPER_TAR_FORM_CHANGE_ITINERARY = 'IMMAPER_TAR_FORM_CHANGE_ITINERARY'
export const IMMAPER_TAR_FORM_ONCHANGE = 'IMMAPER_TAR_FORM_ONCHANGE'
export const IMMAPER_TAR_FORM_RESET = 'IMMAPER_TAR_FORM_RESET'


