export const SET_IMMAP_OFFICE_FORMDATA = 'SET_IMMAP_OFFICE_FORMDATA';
export const SET_BULK_IMMAP_OFFICE_FORMDATA = 'SET_BULK_IMMAP_OFFICE_FORMDATA';
export const RESET_IMMAP_OFFICE_FORMDATA = 'RESET_IMMAP_OFFICE_FORMDATA';
