export const SET_RECOMMENDATION_DATA = 'SET_RECOMMENDATION_DATA';
export const SET_BULK_RECOMMENDATION_DATA = 'SET_BULK_RECOMMENDATION_DATA';
export const RESET_RECOMMENDATION_DATA = 'RESET_RECOMMENDATION_DATA';
