// define types for webActions and webReducer
export const SET_SIDEBAR_ACTIVE = 'SET_SIDEBAR_ACTIVE';
export const SET_OPEN_SIDEBAR = 'SET_OPEN_SIDEBAR';
export const SET_HIDE_SIDEBAR = 'SET_HIDE_SIDEBAR';
export const SET_MOBILE_MENU = 'SET_MOBILE_MENU';
export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE';
export const DELETE_ALL_FLASH_MESSAGE = 'DELETE_ALL_FLASH_MESSAGE';
export const SHOW_LOADING = 'SHOW_LOADING';
export const CHECK_ERROR_FORM = 'CHECK_ERROR_FORM';
export const SET_SPINNER = 'SET_SPINNER';
