<?php

return [
    "Africa/Abidjan",
    "Africa/Accra",
    "Africa/Algiers",
    "Africa/Bissau",
    "Africa/Cairo",
    "Africa/Casablanca",
    "Africa/Ceuta",
    "Africa/El_Aaiun",
    "Africa/Johannesburg",
    "Africa/Juba",
    "Africa/Khartoum",
    "Africa/Lagos",
    "Africa/Maputo",
    "Africa/Monrovia",
    "Africa/Nairobi",
    "Africa/Ndjamena",
    "Africa/Sao_Tome",
    "Africa/Tripoli",
    "Africa/Tunis",
    "Africa/Windhoek",
    "America/Adak",
    "America/Anchorage",
    "America/Araguaina",
    "America/Argentina/Buenos_Aires",
    "America/Argentina/Catamarca",
    "America/Argentina/Cordoba",
    "America/Argentina/Jujuy",
    "America/Argentina/La_Rioja",
    "America/Argentina/Mendoza",
    "America/Argentina/Rio_Gallegos",
    "America/Argentina/Salta",
    "America/Argentina/San_Juan",
    "America/Argentina/San_Luis",
    "America/Argentina/Tucuman",
    "America/Argentina/Ushuaia",
    "America/Asuncion",
    "America/Atikokan",
    "America/Bahia",
    "America/Bahia_Banderas",
    "America/Barbados",
    "America/Belem",
    "America/Belize",
    "America/Blanc-Sablon",
    "America/Boa_Vista",
    "America/Bogota",
    "America/Boise",
    "America/Cambridge_Bay",
    "America/Campo_Grande",
    "America/Cancun",
    "America/Caracas",
    "America/Cayenne",
    "America/Chicago",
    "America/Chihuahua",
    "America/Costa_Rica",
    "America/Creston",
    "America/Cuiaba",
    "America/Curacao",
    "America/Danmarkshavn",
    "America/Dawson",
    "America/Dawson_Creek",
    "America/Denver",
    "America/Detroit",
    "America/Edmonton",
    "America/Eirunepe",
    "America/El_Salvador",
    "America/Fort_Nelson",
    "America/Fortaleza",
    "America/Glace_Bay",
    "America/Godthab",
    "America/Goose_Bay",
    "America/Grand_Turk",
    "America/Guatemala",
    "America/Guayaquil",
    "America/Guyana",
    "America/Halifax",
    "America/Havana",
    "America/Hermosillo",
    "America/Indiana/Indianapolis",
    "America/Indiana/Knox",
    "America/Indiana/Marengo",
    "America/Indiana/Petersburg",
    "America/Indiana/Tell_City",
    "America/Indiana/Vevay",
    "America/Indiana/Vincennes",
    "America/Indiana/Winamac",
    "America/Inuvik",
    "America/Iqaluit",
    "America/Jamaica",
    "America/Juneau",
    "America/Kentucky/Louisville",
    "America/Kentucky/Monticello",
    "America/La_Paz",
    "America/Lima",
    "America/Los_Angeles",
    "America/Maceio",
    "America/Managua",
    "America/Manaus",
    "America/Martinique",
    "America/Matamoros",
    "America/Mazatlan",
    "America/Menominee",
    "America/Merida",
    "America/Metlakatla",
    "America/Mexico_City",
    "America/Miquelon",
    "America/Moncton",
    "America/Monterrey",
    "America/Montevideo",
    "America/Nassau",
    "America/New_York",
    "America/Nipigon",
    "America/Nome",
    "America/Noronha",
    "America/North_Dakota/Beulah",
    "America/North_Dakota/Center",
    "America/North_Dakota/New_Salem",
    "America/Ojinaga",
    "America/Panama",
    "America/Pangnirtung",
    "America/Paramaribo",
    "America/Phoenix",
    "America/Port-au-Prince",
    "America/Port_of_Spain",
    "America/Porto_Velho",
    "America/Puerto_Rico",
    "America/Punta_Arenas",
    "America/Rainy_River",
    "America/Rankin_Inlet",
    "America/Recife",
    "America/Regina",
    "America/Resolute",
    "America/Rio_Branco",
    "America/Santarem",
    "America/Santiago",
    "America/Santo_Domingo",
    "America/Sao_Paulo",
    "America/Scoresbysund",
    "America/Sitka",
    "America/St_Johns",
    "America/Swift_Current",
    "America/Tegucigalpa",
    "America/Thule",
    "America/Thunder_Bay",
    "America/Tijuana",
    "America/Toronto",
    "America/Vancouver",
    "America/Whitehorse",
    "America/Winnipeg",
    "America/Yakutat",
    "America/Yellowknife",
    "Antarctica/Casey",
    "Antarctica/Davis",
    "Antarctica/DumontDUrville",
    "Antarctica/Macquarie",
    "Antarctica/Mawson",
    "Antarctica/Palmer",
    "Antarctica/Rothera",
    "Antarctica/Syowa",
    "Antarctica/Troll",
    "Antarctica/Vostok",
    "Asia/Almaty",
    "Asia/Amman",
    "Asia/Anadyr",
    "Asia/Aqtau",
    "Asia/Aqtobe",
    "Asia/Ashgabat",
    "Asia/Atyrau",
    "Asia/Baghdad",
    "Asia/Baku",
    "Asia/Bangkok",
    "Asia/Barnaul",
    "Asia/Beirut",
    "Asia/Bishkek",
    "Asia/Brunei",
    "Asia/Chita",
    "Asia/Choibalsan",
    "Asia/Colombo",
    "Asia/Damascus",
    "Asia/Dhaka",
    "Asia/Dili",
    "Asia/Dubai",
    "Asia/Dushanbe",
    "Asia/Famagusta",
    "Asia/Gaza",
    "Asia/Hebron",
    "Asia/Ho_Chi_Minh",
    "Asia/Hong_Kong",
    "Asia/Hovd",
    "Asia/Irkutsk",
    "Asia/Jakarta",
    "Asia/Jayapura",
    "Asia/Jerusalem",
    "Asia/Kabul",
    "Asia/Kamchatka",
    "Asia/Karachi",
    "Asia/Kathmandu",
    "Asia/Khandyga",
    "Asia/Kolkata",
    "Asia/Krasnoyarsk",
    "Asia/Kuala_Lumpur",
    "Asia/Kuching",
    "Asia/Macau",
    "Asia/Magadan",
    "Asia/Makassar",
    "Asia/Manila",
    "Asia/Nicosia",
    "Asia/Novokuznetsk",
    "Asia/Novosibirsk",
    "Asia/Omsk",
    "Asia/Oral",
    "Asia/Pontianak",
    "Asia/Pyongyang",
    "Asia/Qatar",
    "Asia/Qostanay",
    "Asia/Qyzylorda",
    "Asia/Riyadh",
    "Asia/Sakhalin",
    "Asia/Samarkand",
    "Asia/Seoul",
    "Asia/Shanghai",
    "Asia/Singapore",
    "Asia/Srednekolymsk",
    "Asia/Taipei",
    "Asia/Tashkent",
    "Asia/Tbilisi",
    "Asia/Tehran",
    "Asia/Thimphu",
    "Asia/Tokyo",
    "Asia/Tomsk",
    "Asia/Ulaanbaatar",
    "Asia/Urumqi",
    "Asia/Ust-Nera",
    "Asia/Vladivostok",
    "Asia/Yakutsk",
    "Asia/Yangon",
    "Asia/Yekaterinburg",
    "Asia/Yerevan",
    "Atlantic/Azores",
    "Atlantic/Bermuda",
    "Atlantic/Canary",
    "Atlantic/Cape_Verde",
    "Atlantic/Faroe",
    "Atlantic/Madeira",
    "Atlantic/Reykjavik",
    "Atlantic/South_Georgia",
    "Atlantic/Stanley",
    "Australia/Adelaide",
    "Australia/Brisbane",
    "Australia/Broken_Hill",
    "Australia/Currie",
    "Australia/Darwin",
    "Australia/Eucla",
    "Australia/Hobart",
    "Australia/Lindeman",
    "Australia/Lord_Howe",
    "Australia/Melbourne",
    "Australia/Perth",
    "Australia/Sydney",
    "CET",
    "CST6CDT",
    "EET",
    "EST",
    "EST5EDT",
    "Etc/GMT",
    "Etc/GMT+1",
    "Etc/GMT+10",
    "Etc/GMT+11",
    "Etc/GMT+12",
    "Etc/GMT+2",
    "Etc/GMT+3",
    "Etc/GMT+4",
    "Etc/GMT+5",
    "Etc/GMT+6",
    "Etc/GMT+7",
    "Etc/GMT+8",
    "Etc/GMT+9",
    "Etc/GMT-1",
    "Etc/GMT-10",
    "Etc/GMT-11",
    "Etc/GMT-12",
    "Etc/GMT-13",
    "Etc/GMT-14",
    "Etc/GMT-2",
    "Etc/GMT-3",
    "Etc/GMT-4",
    "Etc/GMT-5",
    "Etc/GMT-6",
    "Etc/GMT-7",
    "Etc/GMT-8",
    "Etc/GMT-9",
    "Etc/UTC",
    "Europe/Amsterdam",
    "Europe/Andorra",
    "Europe/Astrakhan",
    "Europe/Athens",
    "Europe/Belgrade",
    "Europe/Berlin",
    "Europe/Brussels",
    "Europe/Bucharest",
    "Europe/Budapest",
    "Europe/Chisinau",
    "Europe/Copenhagen",
    "Europe/Dublin",
    "Europe/Gibraltar",
    "Europe/Helsinki",
    "Europe/Istanbul",
    "Europe/Kaliningrad",
    "Europe/Kiev",
    "Europe/Kirov",
    "Europe/Lisbon",
    "Europe/London",
    "Europe/Luxembourg",
    "Europe/Madrid",
    "Europe/Malta",
    "Europe/Minsk",
    "Europe/Monaco",
    "Europe/Moscow",
    "Europe/Oslo",
    "Europe/Paris",
    "Europe/Prague",
    "Europe/Riga",
    "Europe/Rome",
    "Europe/Samara",
    "Europe/Saratov",
    "Europe/Simferopol",
    "Europe/Sofia",
    "Europe/Stockholm",
    "Europe/Tallinn",
    "Europe/Tirane",
    "Europe/Ulyanovsk",
    "Europe/Uzhgorod",
    "Europe/Vienna",
    "Europe/Vilnius",
    "Europe/Volgograd",
    "Europe/Warsaw",
    "Europe/Zaporozhye",
    "Europe/Zurich",
    "HST",
    "Indian/Chagos",
    "Indian/Christmas",
    "Indian/Cocos",
    "Indian/Kerguelen",
    "Indian/Mahe",
    "Indian/Maldives",
    "Indian/Mauritius",
    "Indian/Reunion",
    "MET",
    "MST",
    "MST7MDT",
    "PST8PDT",
    "Pacific/Apia",
    "Pacific/Auckland",
    "Pacific/Bougainville",
    "Pacific/Chatham",
    "Pacific/Chuuk",
    "Pacific/Easter",
    "Pacific/Efate",
    "Pacific/Enderbury",
    "Pacific/Fakaofo",
    "Pacific/Fiji",
    "Pacific/Funafuti",
    "Pacific/Galapagos",
    "Pacific/Gambier",
    "Pacific/Guadalcanal",
    "Pacific/Guam",
    "Pacific/Honolulu",
    "Pacific/Kiritimati",
    "Pacific/Kosrae",
    "Pacific/Kwajalein",
    "Pacific/Majuro",
    "Pacific/Marquesas",
    "Pacific/Nauru",
    "Pacific/Niue",
    "Pacific/Norfolk",
    "Pacific/Noumea",
    "Pacific/Pago_Pago",
    "Pacific/Palau",
    "Pacific/Pitcairn",
    "Pacific/Pohnpei",
    "Pacific/Port_Moresby",
    "Pacific/Rarotonga",
    "Pacific/Tahiti",
    "Pacific/Tarawa",
    "Pacific/Tongatapu",
    "Pacific/Wake",
    "Pacific/Wallis",
    "WET"

];

// [
//     ['label' => "Africa/Abidjan", 'value' => "+00:00"],
//     ['label' => "Africa/Accra", 'value' => "+00:00"],
//     ['label' => "Africa/Algiers", 'value' => "+01:00"],
//     ['label' => "Africa/Bissau", 'value' => "+00:00"],
//     ['label' => "Africa/Cairo", 'value' => "+02:00"],
//     ['label' => "Africa/Casablanca", 'value' => "+01:00"],
//     ['label' => "Africa/Ceuta", 'value' => "+01:00"],
//     ['label' => "Africa/El_Aaiun", 'value' => "+01:00"],
//     ['label' => "Africa/Johannesburg", 'value' => "+02:00"],
//     ['label' => "Africa/Juba", 'value' => "+03:00"],
//     ['label' => "Africa/Khartoum", 'value' => "+02:00"],
//     ['label' => "Africa/Lagos", 'value' => "+01:00"],
//     ['label' => "Africa/Maputo", 'value' => "+02:00"],
//     ['label' => "Africa/Monrovia", 'value' => "+00:00"],
//     ['label' => "Africa/Nairobi", 'value' => "+03:00"],
//     ['label' => "Africa/Ndjamena", 'value' => "+01:00"],
//     ['label' => "Africa/Sao_Tome", 'value' => "+00:00"],
//     ['label' => "Africa/Tripoli", 'value' => "+02:00"],
//     ['label' => "Africa/Tunis", 'value' => "+01:00"],
//     ['label' => "Africa/Windhoek", 'value' => "+02:00"],
//     ['label' => "America/Adak", 'value' => "-10:00"],
//     ['label' => "America/Anchorage", 'value' => "-09:00"],
//     ['label' => "America/Araguaina", 'value' => "-03:00"],
//     ['label' => "America/Argentina/Buenos_Aires", 'value' => "-03:00"],
//     ['label' => "America/Argentina/Catamarca", 'value' => "-03:00"],
//     ['label' => "America/Argentina/Cordoba", 'value' => "-03:00"],
//     ['label' => "America/Argentina/Jujuy", 'value' => "-03:00"],
//     ['label' => "America/Argentina/La_Rioja", 'value' => "-03:00"],
//     ['label' => "America/Argentina/Mendoza", 'value' => "-03:00"],
//     ['label' => "America/Argentina/Rio_Gallegos", 'value' => "-03:00"],
//     ['label' => "America/Argentina/Salta", 'value' => "-03:00"],
//     ['label' => "America/Argentina/San_Juan", 'value' => "-03:00"],
//     ['label' => "America/Argentina/San_Luis", 'value' => "-03:00"],
//     ['label' => "America/Argentina/Tucuman", 'value' => "-03:00"],
//     ['label' => "America/Argentina/Ushuaia", 'value' => "-03:00"],
//     ['label' => "America/Asuncion", 'value' => "-03:00"],
//     ['label' => "America/Atikokan", 'value' => "-05:00"],
//     ['label' => "America/Bahia", 'value' => "-03:00"],
//     ['label' => "America/Bahia_Banderas", 'value' => ""],
//     ['label' => "America/Barbados", 'value' => ""],
//     ['label' => "America/Belem", 'value' => ""],
//     ['label' => "America/Belize", 'value' => ""],
//     ['label' => "America/Blanc-Sablon", 'value' => ""],
//     ['label' => "America/Boa_Vista", 'value' => ""],
//     ['label' => "America/Bogota", 'value' => ""],
//     ['label' => "America/Boise", 'value' => ""],
//     ['label' => "America/Cambridge_Bay", 'value' => ""],
//     ['label' => "America/Campo_Grande", 'value' => ""],
//     ['label' => "America/Cancun", 'value' => ""],
//     ['label' => "America/Caracas", 'value' => ""],
//     ['label' => "America/Cayenne", 'value' => ""],
//     ['label' => "America/Chicago", 'value' => ""],
//     ['label' => "America/Chihuahua", 'value' => ""],
//     ['label' => "America/Costa_Rica", 'value' => ""],
//     ['label' => "America/Creston", 'value' => ""],
//     ['label' => "America/Cuiaba", 'value' => ""],
//     ['label' => "America/Curacao", 'value' => ""],
//     ['label' => "America/Danmarkshavn", 'value' => ""],
//     ['label' => "America/Dawson", 'value' => ""],
//     ['label' => "America/Dawson_Creek", 'value' => ""],
//     ['label' => "America/Denver", 'value' => ""],
//     ['label' => "America/Detroit", 'value' => ""],
//     ['label' => "America/Edmonton", 'value' => ""],
//     ['label' => "America/Eirunepe", 'value' => ""],
//     ['label' => "America/El_Salvador", 'value' => ""],
//     ['label' => "America/Fort_Nelson", 'value' => ""],
//     ['label' => "America/Fortaleza", 'value' => ""],
//     ['label' => "America/Glace_Bay", 'value' => ""],
//     ['label' => "America/Godthab", 'value' => ""],
//     ['label' => "America/Goose_Bay", 'value' => ""],
//     ['label' => "America/Grand_Turk", 'value' => ""],
//     ['label' => "America/Guatemala", 'value' => ""],
//     ['label' => "America/Guayaquil", 'value' => ""],
//     ['label' => "America/Guyana", 'value' => ""],
//     ['label' => "America/Halifax", 'value' => ""],
//     ['label' => "America/Havana", 'value' => ""],
//     ['label' => "America/Hermosillo", 'value' => ""],
//     ['label' => "America/Indiana/Indianapolis", 'value' => ""],
//     ['label' => "America/Indiana/Knox", 'value' => ""],
//     ['label' => "America/Indiana/Marengo", 'value' => ""],
//     ['label' => "America/Indiana/Petersburg", 'value' => ""],
//     ['label' => "America/Indiana/Tell_City", 'value' => ""],
//     ['label' => "America/Indiana/Vevay", 'value' => ""],
//     ['label' => "America/Indiana/Vincennes", 'value' => ""],
//     ['label' => "America/Indiana/Winamac", 'value' => ""],
//     ['label' => "America/Inuvik", 'value' => ""],
//     ['label' => "America/Iqaluit", 'value' => ""],
//     ['label' => "America/Jamaica", 'value' => ""],
//     ['label' => "America/Juneau", 'value' => ""],
//     ['label' => "America/Kentucky/Louisville", 'value' => ""],
//     ['label' => "America/Kentucky/Monticello", 'value' => ""],
//     ['label' => "America/La_Paz", 'value' => ""],
//     ['label' => "America/Lima", 'value' => ""],
//     ['label' => "America/Los_Angeles", 'value' => ""],
//     ['label' => "America/Maceio", 'value' => ""],
//     ['label' => "America/Managua", 'value' => ""],
//     ['label' => "America/Manaus", 'value' => ""],
//     ['label' => "America/Martinique", 'value' => ""],
//     ['label' => "America/Matamoros", 'value' => ""],
//     ['label' => "America/Mazatlan", 'value' => ""],
//     ['label' => "America/Menominee", 'value' => ""],
//     ['label' => "America/Merida", 'value' => ""],
//     ['label' => "America/Metlakatla", 'value' => ""],
//     ['label' => "America/Mexico_City", 'value' => ""],
//     ['label' => "America/Miquelon", 'value' => ""],
//     ['label' => "America/Moncton", 'value' => ""],
//     ['label' => "America/Monterrey", 'value' => ""],
//     ['label' => "America/Montevideo", 'value' => ""],
//     ['label' => "America/Nassau", 'value' => ""],
//     ['label' => "America/New_York", 'value' => ""],
//     ['label' => "America/Nipigon", 'value' => ""],
//     ['label' => "America/Nome", 'value' => ""],
//     ['label' => "America/Noronha", 'value' => ""],
//     ['label' => "America/North_Dakota/Beulah", 'value' => ""],
//     ['label' => "America/North_Dakota/Center", 'value' => ""],
//     ['label' => "America/North_Dakota/New_Salem", 'value' => ""],
//     ['label' => "America/Ojinaga", 'value' => ""],
//     ['label' => "America/Panama", 'value' => ""],
//     ['label' => "America/Pangnirtung", 'value' => ""],
//     ['label' => "America/Paramaribo", 'value' => ""],
//     ['label' => "America/Phoenix", 'value' => ""],
//     ['label' => "America/Port-au-Prince", 'value' => ""],
//     ['label' => "America/Port_of_Spain", 'value' => ""],
//     ['label' => "America/Porto_Velho", 'value' => ""],
//     ['label' => "America/Puerto_Rico", 'value' => ""],
//     ['label' => "America/Punta_Arenas", 'value' => ""],
//     ['label' => "America/Rainy_River", 'value' => ""],
//     ['label' => "America/Rankin_Inlet", 'value' => ""],
//     ['label' => "America/Recife", 'value' => ""],
//     ['label' => "America/Regina", 'value' => ""],
//     ['label' => "America/Resolute", 'value' => ""],
//     ['label' => "America/Rio_Branco", 'value' => ""],
//     ['label' => "America/Santarem", 'value' => ""],
//     ['label' => "America/Santiago", 'value' => ""],
//     ['label' => "America/Santo_Domingo", 'value' => ""],
//     ['label' => "America/Sao_Paulo", 'value' => ""],
//     ['label' => "America/Scoresbysund", 'value' => ""],
//     ['label' => "America/Sitka", 'value' => ""],
//     ['label' => "America/St_Johns", 'value' => ""],
//     ['label' => "America/Swift_Current", 'value' => ""],
//     ['label' => "America/Tegucigalpa", 'value' => ""],
//     ['label' => "America/Thule", 'value' => ""],
//     ['label' => "America/Thunder_Bay", 'value' => ""],
//     ['label' => "America/Tijuana", 'value' => ""],
//     ['label' => "America/Toronto", 'value' => ""],
//     ['label' => "America/Vancouver", 'value' => ""],
//     ['label' => "America/Whitehorse", 'value' => ""],
//     ['label' => "America/Winnipeg", 'value' => ""],
//     ['label' => "America/Yakutat", 'value' => ""],
//     ['label' => "America/Yellowknife", 'value' => ""],
//     ['label' => "Antarctica/Casey", 'value' => ""],
//     ['label' => "Antarctica/Davis", 'value' => ""],
//     ['label' => "Antarctica/DumontDUrville", 'value' => ""],
//     ['label' => "Antarctica/Macquarie", 'value' => ""],
//     ['label' => "Antarctica/Mawson", 'value' => ""],
//     ['label' => "Antarctica/Palmer", 'value' => ""],
//     ['label' => "Antarctica/Rothera", 'value' => ""],
//     ['label' => "Antarctica/Syowa", 'value' => ""],
//     ['label' => "Antarctica/Troll", 'value' => ""],
//     ['label' => "Antarctica/Vostok", 'value' => ""],
//     ['label' => "Asia/Almaty", 'value' => ""],
//     ['label' => "Asia/Amman", 'value' => ""],
//     ['label' => "Asia/Anadyr", 'value' => ""],
//     ['label' => "Asia/Aqtau", 'value' => ""],
//     ['label' => "Asia/Aqtobe", 'value' => ""],
//     ['label' => "Asia/Ashgabat", 'value' => ""],
//     ['label' => "Asia/Atyrau", 'value' => ""],
//     ['label' => "Asia/Baghdad", 'value' => ""],
//     ['label' => "Asia/Baku", 'value' => ""],
//     ['label' => "Asia/Bangkok", 'value' => ""],
//     ['label' => "Asia/Barnaul", 'value' => ""],
//     ['label' => "Asia/Beirut", 'value' => ""],
//     ['label' => "Asia/Bishkek", 'value' => ""],
//     ['label' => "Asia/Brunei", 'value' => ""],
//     ['label' => "Asia/Chita", 'value' => ""],
//     ['label' => "Asia/Choibalsan", 'value' => ""],
//     ['label' => "Asia/Colombo", 'value' => ""],
//     ['label' => "Asia/Damascus", 'value' => ""],
//     ['label' => "Asia/Dhaka", 'value' => ""],
//     ['label' => "Asia/Dili", 'value' => ""],
//     ['label' => "Asia/Dubai", 'value' => ""],
//     ['label' => "Asia/Dushanbe", 'value' => ""],
//     ['label' => "Asia/Famagusta", 'value' => ""],
//     ['label' => "Asia/Gaza", 'value' => ""],
//     ['label' => "Asia/Hebron", 'value' => ""],
//     ['label' => "Asia/Ho_Chi_Minh", 'value' => ""],
//     ['label' => "Asia/Hong_Kong", 'value' => ""],
//     ['label' => "Asia/Hovd", 'value' => ""],
//     ['label' => "Asia/Irkutsk", 'value' => ""],
//     ['label' => "Asia/Jakarta", 'value' => ""],
//     ['label' => "Asia/Jayapura", 'value' => ""],
//     ['label' => "Asia/Jerusalem", 'value' => ""],
//     ['label' => "Asia/Kabul", 'value' => ""],
//     ['label' => "Asia/Kamchatka", 'value' => ""],
//     ['label' => "Asia/Karachi", 'value' => ""],
//     ['label' => "Asia/Kathmandu", 'value' => ""],
//     ['label' => "Asia/Khandyga", 'value' => ""],
//     ['label' => "Asia/Kolkata", 'value' => ""],
//     ['label' => "Asia/Krasnoyarsk", 'value' => ""],
//     ['label' => "Asia/Kuala_Lumpur", 'value' => ""],
//     ['label' => "Asia/Kuching", 'value' => ""],
//     ['label' => "Asia/Macau", 'value' => ""],
//     ['label' => "Asia/Magadan", 'value' => ""],
//     ['label' => "Asia/Makassar", 'value' => ""],
//     ['label' => "Asia/Manila", 'value' => ""],
//     ['label' => "Asia/Nicosia", 'value' => ""],
//     ['label' => "Asia/Novokuznetsk", 'value' => ""],
//     ['label' => "Asia/Novosibirsk", 'value' => ""],
//     ['label' => "Asia/Omsk", 'value' => ""],
//     ['label' => "Asia/Oral", 'value' => ""],
//     ['label' => "Asia/Pontianak", 'value' => ""],
//     ['label' => "Asia/Pyongyang", 'value' => ""],
//     ['label' => "Asia/Qatar", 'value' => ""],
//     ['label' => "Asia/Qostanay", 'value' => ""],
//     ['label' => "Asia/Qyzylorda", 'value' => ""],
//     ['label' => "Asia/Riyadh", 'value' => ""],
//     ['label' => "Asia/Sakhalin", 'value' => ""],
//     ['label' => "Asia/Samarkand", 'value' => ""],
//     ['label' => "Asia/Seoul", 'value' => ""],
//     ['label' => "Asia/Shanghai", 'value' => ""],
//     ['label' => "Asia/Singapore", 'value' => ""],
//     ['label' => "Asia/Srednekolymsk", 'value' => ""],
//     ['label' => "Asia/Taipei", 'value' => ""],
//     ['label' => "Asia/Tashkent", 'value' => ""],
//     ['label' => "Asia/Tbilisi", 'value' => ""],
//     ['label' => "Asia/Tehran", 'value' => ""],
//     ['label' => "Asia/Thimphu", 'value' => ""],
//     ['label' => "Asia/Tokyo", 'value' => ""],
//     ['label' => "Asia/Tomsk", 'value' => ""],
//     ['label' => "Asia/Ulaanbaatar", 'value' => ""],
//     ['label' => "Asia/Urumqi", 'value' => ""],
//     ['label' => "Asia/Ust-Nera", 'value' => ""],
//     ['label' => "Asia/Vladivostok", 'value' => ""],
//     ['label' => "Asia/Yakutsk", 'value' => ""],
//     ['label' => "Asia/Yangon", 'value' => ""],
//     ['label' => "Asia/Yekaterinburg", 'value' => ""],
//     ['label' => "Asia/Yerevan", 'value' => ""],
//     ['label' => "Atlantic/Azores", 'value' => ""],
//     ['label' => "Atlantic/Bermuda", 'value' => ""],
//     ['label' => "Atlantic/Canary", 'value' => ""],
//     ['label' => "Atlantic/Cape_Verde", 'value' => ""],
//     ['label' => "Atlantic/Faroe", 'value' => ""],
//     ['label' => "Atlantic/Madeira", 'value' => ""],
//     ['label' => "Atlantic/Reykjavik", 'value' => ""],
//     ['label' => "Atlantic/South_Georgia", 'value' => ""],
//     ['label' => "Atlantic/Stanley", 'value' => ""],
//     ['label' => "Australia/Adelaide", 'value' => ""],
//     ['label' => "Australia/Brisbane", 'value' => ""],
//     ['label' => "Australia/Broken_Hill", 'value' => ""],
//     ['label' => "Australia/Currie", 'value' => ""],
//     ['label' => "Australia/Darwin", 'value' => ""],
//     ['label' => "Australia/Eucla", 'value' => ""],
//     ['label' => "Australia/Hobart", 'value' => ""],
//     ['label' => "Australia/Lindeman", 'value' => ""],
//     ['label' => "Australia/Lord_Howe", 'value' => ""],
//     ['label' => "Australia/Melbourne", 'value' => ""],
//     ['label' => "Australia/Perth", 'value' => ""],
//     ['label' => "Australia/Sydney", 'value' => ""],
//     ['label' => "CET", 'value' => ""],
//     ['label' => "CST6CDT", 'value' => ""],
//     ['label' => "EET", 'value' => ""],
//     ['label' => "EST", 'value' => ""],
//     ['label' => "EST5EDT", 'value' => ""],
//     ['label' => "Etc/GMT", 'value' => ""],
//     ['label' => "Etc/GMT+1", 'value' => ""],
//     ['label' => "Etc/GMT+10", 'value' => ""],
//     ['label' => "Etc/GMT+11", 'value' => ""],
//     ['label' => "Etc/GMT+12", 'value' => ""],
//     ['label' => "Etc/GMT+2", 'value' => ""],
//     ['label' => "Etc/GMT+3", 'value' => ""],
//     ['label' => "Etc/GMT+4", 'value' => ""],
//     ['label' => "Etc/GMT+5", 'value' => ""],
//     ['label' => "Etc/GMT+6", 'value' => ""],
//     ['label' => "Etc/GMT+7", 'value' => ""],
//     ['label' => "Etc/GMT+8", 'value' => ""],
//     ['label' => "Etc/GMT+9", 'value' => ""],
//     ['label' => "Etc/GMT-1", 'value' => ""],
//     ['label' => "Etc/GMT-10", 'value' => ""],
//     ['label' => "Etc/GMT-11", 'value' => ""],
//     ['label' => "Etc/GMT-12", 'value' => ""],
//     ['label' => "Etc/GMT-13", 'value' => ""],
//     ['label' => "Etc/GMT-14", 'value' => ""],
//     ['label' => "Etc/GMT-2", 'value' => ""],
//     ['label' => "Etc/GMT-3", 'value' => ""],
//     ['label' => "Etc/GMT-4", 'value' => ""],
//     ['label' => "Etc/GMT-5", 'value' => ""],
//     ['label' => "Etc/GMT-6", 'value' => ""],
//     ['label' => "Etc/GMT-7", 'value' => ""],
//     ['label' => "Etc/GMT-8", 'value' => ""],
//     ['label' => "Etc/GMT-9", 'value' => ""],
//     ['label' => "Etc/UTC", 'value' => ""],
//     ['label' => "Europe/Amsterdam", 'value' => ""],
//     ['label' => "Europe/Andorra", 'value' => ""],
//     ['label' => "Europe/Astrakhan", 'value' => ""],
//     ['label' => "Europe/Athens", 'value' => ""],
//     ['label' => "Europe/Belgrade", 'value' => ""],
//     ['label' => "Europe/Berlin", 'value' => ""],
//     ['label' => "Europe/Brussels", 'value' => ""],
//     ['label' => "Europe/Bucharest", 'value' => ""],
//     ['label' => "Europe/Budapest", 'value' => ""],
//     ['label' => "Europe/Chisinau", 'value' => ""],
//     ['label' => "Europe/Copenhagen", 'value' => ""],
//     ['label' => "Europe/Dublin", 'value' => ""],
//     ['label' => "Europe/Gibraltar", 'value' => ""],
//     ['label' => "Europe/Helsinki", 'value' => ""],
//     ['label' => "Europe/Istanbul", 'value' => ""],
//     ['label' => "Europe/Kaliningrad", 'value' => ""],
//     ['label' => "Europe/Kiev", 'value' => ""],
//     ['label' => "Europe/Kirov", 'value' => ""],
//     ['label' => "Europe/Lisbon", 'value' => ""],
//     ['label' => "Europe/London", 'value' => ""],
//     ['label' => "Europe/Luxembourg", 'value' => ""],
//     ['label' => "Europe/Madrid", 'value' => ""],
//     ['label' => "Europe/Malta", 'value' => ""],
//     ['label' => "Europe/Minsk", 'value' => ""],
//     ['label' => "Europe/Monaco", 'value' => ""],
//     ['label' => "Europe/Moscow", 'value' => ""],
//     ['label' => "Europe/Oslo", 'value' => ""],
//     ['label' => "Europe/Paris", 'value' => ""],
//     ['label' => "Europe/Prague", 'value' => ""],
//     ['label' => "Europe/Riga", 'value' => ""],
//     ['label' => "Europe/Rome", 'value' => ""],
//     ['label' => "Europe/Samara", 'value' => ""],
//     ['label' => "Europe/Saratov", 'value' => ""],
//     ['label' => "Europe/Simferopol", 'value' => ""],
//     ['label' => "Europe/Sofia", 'value' => ""],
//     ['label' => "Europe/Stockholm", 'value' => ""],
//     ['label' => "Europe/Tallinn", 'value' => ""],
//     ['label' => "Europe/Tirane", 'value' => ""],
//     ['label' => "Europe/Ulyanovsk", 'value' => ""],
//     ['label' => "Europe/Uzhgorod", 'value' => ""],
//     ['label' => "Europe/Vienna", 'value' => ""],
//     ['label' => "Europe/Vilnius", 'value' => ""],
//     ['label' => "Europe/Volgograd", 'value' => ""],
//     ['label' => "Europe/Warsaw", 'value' => ""],
//     ['label' => "Europe/Zaporozhye", 'value' => ""],
//     ['label' => "Europe/Zurich", 'value' => ""],
//     ['label' => "HST", 'value' => ""],
//     ['label' => "Indian/Chagos", 'value' => ""],
//     ['label' => "Indian/Christmas", 'value' => ""],
//     ['label' => "Indian/Cocos", 'value' => ""],
//     ['label' => "Indian/Kerguelen", 'value' => ""],
//     ['label' => "Indian/Mahe", 'value' => ""],
//     ['label' => "Indian/Maldives", 'value' => ""],
//     ['label' => "Indian/Mauritius", 'value' => ""],
//     ['label' => "Indian/Reunion", 'value' => ""],
//     ['label' => "MET", 'value' => ""],
//     ['label' => "MST", 'value' => ""],
//     ['label' => "MST7MDT", 'value' => ""],
//     ['label' => "PST8PDT", 'value' => ""],
//     ['label' => "Pacific/Apia", 'value' => ""],
//     ['label' => "Pacific/Auckland", 'value' => ""],
//     ['label' => "Pacific/Bougainville", 'value' => ""],
//     ['label' => "Pacific/Chatham", 'value' => ""],
//     ['label' => "Pacific/Chuuk", 'value' => ""],
//     ['label' => "Pacific/Easter", 'value' => ""],
//     ['label' => "Pacific/Efate", 'value' => ""],
//     ['label' => "Pacific/Enderbury", 'value' => ""],
//     ['label' => "Pacific/Fakaofo", 'value' => ""],
//     ['label' => "Pacific/Fiji", 'value' => ""],
//     ['label' => "Pacific/Funafuti", 'value' => ""],
//     ['label' => "Pacific/Galapagos", 'value' => ""],
//     ['label' => "Pacific/Gambier", 'value' => ""],
//     ['label' => "Pacific/Guadalcanal", 'value' => ""],
//     ['label' => "Pacific/Guam", 'value' => ""],
//     ['label' => "Pacific/Honolulu", 'value' => ""],
//     ['label' => "Pacific/Kiritimati", 'value' => ""],
//     ['label' => "Pacific/Kosrae", 'value' => ""],
//     ['label' => "Pacific/Kwajalein", 'value' => ""],
//     ['label' => "Pacific/Majuro", 'value' => ""],
//     ['label' => "Pacific/Marquesas", 'value' => ""],
//     ['label' => "Pacific/Nauru", 'value' => ""],
//     ['label' => "Pacific/Niue", 'value' => ""],
//     ['label' => "Pacific/Norfolk", 'value' => ""],
//     ['label' => "Pacific/Noumea", 'value' => ""],
//     ['label' => "Pacific/Pago_Pago", 'value' => ""],
//     ['label' => "Pacific/Palau", 'value' => ""],
//     ['label' => "Pacific/Pitcairn", 'value' => ""],
//     ['label' => "Pacific/Pohnpei", 'value' => ""],
//     ['label' => "Pacific/Port_Moresby", 'value' => ""],
//     ['label' => "Pacific/Rarotonga", 'value' => ""],
//     ['label' => "Pacific/Tahiti", 'value' => ""],
//     ['label' => "Pacific/Tarawa", 'value' => ""],
//     ['label' => "Pacific/Tongatapu", 'value' => ""],
//     ['label' => "Pacific/Wake", 'value' => ""],
//     ['label' => "Pacific/Wallis", 'value' => ""],
//     ['label' => "WET", 'value' => ""]
// ];
