export const SET_JOB_RECOMMENDATION_FILTER_DATA = 'SET_JOB_RECOMMENDATION_FILTER_DATA';
export const RESET_JOB_RECOMMENDATION_FILTER_DATA = 'RESET_JOB_RECOMMENDATION_FILTER_DATA';
export const RESET_JOB_RECOMMENDATION_PARAMETERS = 'RESET_JOB_RECOMMENDATION_PARAMETERS';
export const RESET_JOB_RECOMMENDATION_FILTER = 'RESET_JOB_RECOMMENDATION_FILTER';
