export const SET_JOB_RECOMMENDATION = 'SET_JOB_RECOMMENDATION';
export const SET_BULK_JOB_RECOMMENDATION = 'SET_BULK_JOB_RECOMMENDATION';
export const RESET_JOB_RECOMMENDATION = 'RESET_JOB_RECOMMENDATION';
